import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.css'
import React from 'react'
import ReduxProvider from 'src/store/ReduxProvider'

const montserrat = Montserrat({
  variable: '--font-montserrat',
  subsets: ['cyrillic'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type RootProps = Readonly<{
  children: React.ReactNode
}>

const RootLayout: React.FC<Readonly<RootProps>> = ({ children }) => {
  return (
    <html lang="en">
      <ReduxProvider>
        <body className={`${montserrat.variable}`}>{children}</body>
      </ReduxProvider>
    </html>
  )
}

export default RootLayout
