// app/layout.tsx
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.css'
import ReduxProvider from 'src/store/ReduxProvider'
import { HydrationWrapper } from '@components/HydrationWrapper/HydrationWrapper'

const montserrat = Montserrat({
  variable: '--font-montserrat',
  subsets: ['cyrillic'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={montserrat.variable}>
        <ReduxProvider>
          <HydrationWrapper>{children}</HydrationWrapper>
        </ReduxProvider>
      </body>
    </html>
  )
}
